name: Lint
description: Run linter and type-checker and test

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9.9.0
        run_install: false
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: ./pnpm-lock.yaml
        node-version-file: './package.json'
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Launch Turbo Remote Cache Server
      uses: dtinth/setup-github-actions-caching-for-turbo@v1.3.0
    - name: Run lint / test / type-check
      run: npx turbo run lint test type-check
      shell: bash
