name: CI (example apps)

on:
  push:
    paths:
      - 'examples/**'
      - '.github/workflows/ci-examples.yaml'
      - '.github/actions/build/action.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        apps:
          - todoapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          filter: "examples/${{ matrix.apps }}"
