name: CI (example apps)

on:
  push:
    paths:
      - 'examples/**'
      - 'packages/**'
      - '.github/workflows/ci-examples.yaml'

jobs:
  build:
    strategy:
      matrix:
        apps:
          - todoapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        shell: bash
      - name: Build 
        run: npx turbo run build --filter="${{ matrix.apps }}"
