name: CI (packages)

on:
  push:
    paths:
      - 'packages/**'
      - '.github/workflows/ci-packages.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/ci

  # A job to check if all examples can be built successfully to detect unwanted breaking changes
  build-examples:
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          filter: "examples/*"

  # Once all jobs are successful, publish the packages
  publish-preview:
    needs:
      - ci
      - build-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version-file: './package.json'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - run: pnpx pkg-pr-new publish "./packages/*"
